resources:
- manager.yaml
- service-ca-bundle-configmap.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: nvcr.io/nvidia/cloud-native/nim-operator
  newTag: v1.0.0
