apiVersion: apps.nvidia.com/v1alpha1
kind: NemoGuardrail
metadata:
  name: nemoguardrails-sample
  namespace: nemo
spec:
  # required if a NIM endpoint is hosted by NVIDIA
  configStore:
    pvc:
      name: "pvc-guardrail-config"
      create: true
      storageClass: ""
      volumeAccessMode: ReadWriteOnce
      size: "1Gi"
  nimEndpoint:
    baseURL: "http://meta-llama-3-1-8b-instruct.nemo.svc.cluster.local:8000/v1"
  databaseConfig:
    host: guardrail-pg-postgresql.nemo.svc.cluster.local
    port: 5432
    databaseName: guardraildb
    credentials:
      user: guardrailuser
      secretName: guardrail-pg-existing-secret
      passwordKey: password
  expose:
    service:
      type: ClusterIP
      port: 8000
  image:
    repository: nvcr.io/nvidia/nemo-microservices/guardrails
    tag: "25.10"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  metrics:
    serviceMonitor: {}
  replicas: 1
  resources:
    limits:
      cpu: "1"
      ephemeral-storage: 10Gi
