---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: meta-llama-3-1-8b-instruct
  namespace: nemo
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/meta/llama-3.1-8b-instruct:1.8.6
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        engine: tensorrt_llm
        tensorParallelism: "1"
  storage:
    pvc:
      create: true
      storageClass: ""
      size: "50Gi"
      volumeAccessMode: ReadWriteOnce
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMPipeline
metadata:
  name: llama3-1-8b-pipeline
  namespace: nemo
spec:
  services:
    - name: meta-llama-3-1-8b-instruct
      enabled: true
      spec:
        env:
          - name: NIM_PEFT_SOURCE
            value: http://nemoentitystore-sample.nemo.svc.cluster.local:8000
          - name: NIM_PEFT_REFRESH_INTERVAL
            value: "180"
          - name: NIM_MAX_CPU_LORAS
            value: "16"
          - name: NIM_MAX_GPU_LORAS
            value: "8"
          - name: NIM_GUIDED_DECODING_BACKEND
            value: fast_outlines
        image:
          repository: nvcr.io/nim/meta/llama-3.1-8b-instruct
          tag: 1.8.6
          pullPolicy: IfNotPresent
          pullSecrets:
          - ngc-secret
        authSecret: ngc-api-secret
        storage:
          nimCache:
            name: meta-llama-3-1-8b-instruct
            profile: ''
        replicas: 1
        resources:
          limits:
            nvidia.com/gpu: 1
        expose:
          service:
            type: ClusterIP
            port: 8000
    
