apiVersion: apps.nvidia.com/v1alpha1
kind: NIMPipeline
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: k8s-nim-operator
  name: nimpipeline-sample
spec:
  # TODO(user): Add fields here
