apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: nimcache-sample
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/meta/llama-3.1-8b-instruct:1.3.3
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        profiles: []
        autoDetect: true
        precision: "fp8"
        engine: "tensorrt_llm"
        qosProfile: "throughput"
        gpus:
          product: "l40s"
          ids:
            - "26b5"
        tensorParallelism: "1"
  storage:
    pvc:
      create: true
      storageClass: ""
      size: "50Gi"
      volumeAccessMode: ReadWriteOnce
