# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apps.nvidia.com_nimservices.yaml
- bases/apps.nvidia.com_nimcaches.yaml
- bases/apps.nvidia.com_nimpipelines.yaml
- bases/apps.nvidia.com_nemocustomizers.yaml
- bases/apps.nvidia.com_nemoguardrails.yaml
- bases/apps.nvidia.com_nemoevaluators.yaml
- bases/apps.nvidia.com_nemodatastores.yaml
- bases/apps.nvidia.com_nemoentitystores.yaml
- bases/apps.nvidia.com_nemoservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_nimservices.yaml
#- path: patches/cainjection_in_nimworkflows.yaml
#- path: patches/cainjection_in_nimcaches.yaml
#- path: patches/cainjection_in_nimpipelines.yaml
#- path: patches/cainjection_in_nemocustomizers.yaml
#- path: patches/cainjection_in_nemoguardrails.yaml
#- path: patches/cainjection_in_nemoevaluators.yaml
#- path: patches/cainjection_in_nemodatastores.yaml
#- path: patches/cainjection_in_nemoentitystores.yaml
#- path: patches/cainjection_in_nemoservices.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
